Modified to not hard-code the ant-launcher version.
git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@892684 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/ant b/ant
--- a/ant
+++ b/ant
@@ -25,6 +25,14 @@ else
   JAVA=java
 fi
 
-"$JAVA" -jar framework/base/lib/ant-launcher-1.7.0.jar "$@"
-exit 0
+find_jar() {
+	set -- framework/base/lib/ant-launcher-*.jar
+	if [ $# = 1 ] && [ -e "$1" ]; then
+		echo "$1"
+	else
+		echo "Couldn't find ant-launcher.jar" 1>&2
+		exit 1
+	fi
+}
+"$JAVA" -jar "$(find_jar)" "$@"
 
